### ISSUE TITLE
Downloaded vs Expected Model Name

### ISSUE THREAD

**Issue by oravus** [sakaridis/MGCDA#1]
Hi there,

Thanks for releasing the code. 

While trying to run the instructions for testing on the provided Dark_Zurich dataset, code fails because the file name of the pre-trained model (`refinenet_res101_cityscapes_DarkCityscapes_DarkZurichv3twilight_CycleGANfc_DarkZurichv3night_CycleGANfc_DarkZurich_v3day_labels_original_w_1_v3twilight_labels_adaptedPrevGeoRefDyn_w_1_epoch_10.mat`) 

is different from what is generated by the code 

`(refinenet_res101_cityscapes_DarkCityscapes_DarkZurichTwilight_CycleGANfc_DarkZurichNight_CycleGANfc_DarkZurich_day_labels_original_w_1_twilight_labels_adaptedPrevGeoRefDyn_w_1_epoch_10.mat)`.

What would one need to modify to make it consistent? Our workaround was to hard code it in `source/Semantic_segmentation/Experiments/RefineNet/Union_Cityscapes_Dark_Zurich/scripts/test_mixed.sh`.

**Comment by sakaridis** [comment]
Hi,

Thank you for raising this issue. Indeed, the file name of the pre-trained MGCDA model did not match the name generated by the script. We have updated the name of the shared model file to match the name generated by the script. You don't need to change anything in the code, as the error was in the name of the shared file.

The readme file has been updated accordingly.
