### ISSUE TITLE
 BDD100K-night

### ISSUE THREAD

**Issue by vobecant** [sakaridis/MGCDA#2]
Dear authors,

can you please provide the selected nighttime subset of the segmentation set of BDD100K (at least the IDs)?

Thank you very much in advance.

Best,
Antonin.

**Comment by sakaridis** [comment]
Hi Antonin,

The file names of BDD100K-night are already available in [this text file](../tree/master/data/bdd100k_lists_file_names/images_trainval_night_correct_filenames.txt).

Best,
Christos
