### ISSUE TITLE
Pretrained CycleGAN

### ISSUE THREAD

**Issue by lmjieSCU** [sakaridis/MGCDA#4]
Thank you for your work!
Could you share the pretrained cycleGAN of cityscapes-to-dark_zurich_night?
I'd like to do something with dark_zurich dataset but limited by GPU capacity and speed.
THANKS~

**Comment by sakaridis** [comment]
Done! The readme file is [updated](https://github.com/sakaridis/MGCDA#training-mgcda) with the links to the pretrained CycleGAN generators for translating to twilight and nighttime.
